name: Deploy Multi Repo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: docker build -t kbmegha/client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true kbmegha/client-test npm run test

      - run: docker build -t kbmegha/multi-client ./client
      - run: docker build -t kbmegha/multi-nginx ./nginx
      - run: docker build -t kbmegha/multi-server ./server
      - run: docker build -t kbmegha/multi-worker ./worker

      - run: docker push kbmegha/multi-client
      - run: docker push kbmegha/multi-nginx
      - run: docker push kbmegha/multi-server
      - run: docker push kbmegha/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi-repo
          environment_name: Docker-multi-repo-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-324037294229
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
