name: Deploy Multi Repo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: docker build -t kbmegha/client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true kbmegh/client-test npm run test

      - run: docker build -t kbmegha/multi-client ./client
      - run: docker build -t kbmegha/multi-nginx ./nginx
      - run: docker build -t kbmegha/multi-server ./server
      - run: docker build -t kbmegha/multi-worker ./worker

      - run: docker push -t kbmegha/multi-client ./client
      - run: docker push -t kbmegha/multi-nginx ./nginx
      - run: docker push -t kbmegha/multi-server ./server
      - run: docker push -t kbmegha/multi-worker ./worker
